
# API HealthCheck

GET {{host-url}}//health-check/ping
Authorization: Basic dawid password

###

# API RegisterController

POST {{host-url}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "tobi",
  "password": "password"
}

###

GET {{host-url}}/login
Authorization: Basic tobi password
Accept: application/json

###